// flow-typed signature: 830081dd18be45f4eee815e46ab3be7e
// flow-typed version: <<STUB>>/eslint-plugin-flow_v2.29.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-flow/bin/readmeAssertions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/booleanStyle' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/defineFlowType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/delimiterDangle' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/genericSpacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/noDupeKeys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/noPrimitiveConstructorTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/noWeakTypes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/objectTypeDelimiter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/requireParameterType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/requireReturnType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/requireValidFileAnnotation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/requireVariableType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/semi' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/sortKeys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/spaceAfterTypeColon' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/spaceBeforeGenericBracket' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/spaceBeforeTypeColon' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateFunctions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateObjectTypeIndexer' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateObjectTypeProperty' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateReturnType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateTypeCastExpression' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateTypical' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/reporter' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/typeIdMatch' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/unionIntersectionSpacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/useFlowType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/rules/validSyntax' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/checkFlowFileAnnotation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/fuzzyStringMatch' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/getParameterName' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/getTokenAfterParens' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/getTokenBeforeParens' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/isFlowFile' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/isFlowFileAnnotation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/iterateFunctionNodes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/quoteName' {
  declare module.exports: any;
}

declare module 'eslint-plugin-flow/dist/utilities/spacingFixers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-flow/bin/readmeAssertions.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/bin/readmeAssertions'>;
}
declare module 'eslint-plugin-flow/dist/index.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/index'>;
}
declare module 'eslint-plugin-flow/dist/rules/booleanStyle.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/booleanStyle'>;
}
declare module 'eslint-plugin-flow/dist/rules/defineFlowType.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/defineFlowType'>;
}
declare module 'eslint-plugin-flow/dist/rules/delimiterDangle.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/delimiterDangle'>;
}
declare module 'eslint-plugin-flow/dist/rules/genericSpacing.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/genericSpacing'>;
}
declare module 'eslint-plugin-flow/dist/rules/noDupeKeys.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/noDupeKeys'>;
}
declare module 'eslint-plugin-flow/dist/rules/noPrimitiveConstructorTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/noPrimitiveConstructorTypes'>;
}
declare module 'eslint-plugin-flow/dist/rules/noWeakTypes.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/noWeakTypes'>;
}
declare module 'eslint-plugin-flow/dist/rules/objectTypeDelimiter.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/objectTypeDelimiter'>;
}
declare module 'eslint-plugin-flow/dist/rules/requireParameterType.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/requireParameterType'>;
}
declare module 'eslint-plugin-flow/dist/rules/requireReturnType.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/requireReturnType'>;
}
declare module 'eslint-plugin-flow/dist/rules/requireValidFileAnnotation.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/requireValidFileAnnotation'>;
}
declare module 'eslint-plugin-flow/dist/rules/requireVariableType.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/requireVariableType'>;
}
declare module 'eslint-plugin-flow/dist/rules/semi.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/semi'>;
}
declare module 'eslint-plugin-flow/dist/rules/sortKeys.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/sortKeys'>;
}
declare module 'eslint-plugin-flow/dist/rules/spaceAfterTypeColon.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/spaceAfterTypeColon'>;
}
declare module 'eslint-plugin-flow/dist/rules/spaceBeforeGenericBracket.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/spaceBeforeGenericBracket'>;
}
declare module 'eslint-plugin-flow/dist/rules/spaceBeforeTypeColon.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/spaceBeforeTypeColon'>;
}
declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateFunctions.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateFunctions'>;
}
declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateObjectTypeIndexer.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateObjectTypeIndexer'>;
}
declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateObjectTypeProperty.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateObjectTypeProperty'>;
}
declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateReturnType.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateReturnType'>;
}
declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateTypeCastExpression.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateTypeCastExpression'>;
}
declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateTypical.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/typeColonSpacing/evaluateTypical'>;
}
declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/index.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/typeColonSpacing/index'>;
}
declare module 'eslint-plugin-flow/dist/rules/typeColonSpacing/reporter.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/typeColonSpacing/reporter'>;
}
declare module 'eslint-plugin-flow/dist/rules/typeIdMatch.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/typeIdMatch'>;
}
declare module 'eslint-plugin-flow/dist/rules/unionIntersectionSpacing.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/unionIntersectionSpacing'>;
}
declare module 'eslint-plugin-flow/dist/rules/useFlowType.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/useFlowType'>;
}
declare module 'eslint-plugin-flow/dist/rules/validSyntax.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/rules/validSyntax'>;
}
declare module 'eslint-plugin-flow/dist/utilities/checkFlowFileAnnotation.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/checkFlowFileAnnotation'>;
}
declare module 'eslint-plugin-flow/dist/utilities/fuzzyStringMatch.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/fuzzyStringMatch'>;
}
declare module 'eslint-plugin-flow/dist/utilities/getParameterName.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/getParameterName'>;
}
declare module 'eslint-plugin-flow/dist/utilities/getTokenAfterParens.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/getTokenAfterParens'>;
}
declare module 'eslint-plugin-flow/dist/utilities/getTokenBeforeParens.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/getTokenBeforeParens'>;
}
declare module 'eslint-plugin-flow/dist/utilities/index.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/index'>;
}
declare module 'eslint-plugin-flow/dist/utilities/isFlowFile.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/isFlowFile'>;
}
declare module 'eslint-plugin-flow/dist/utilities/isFlowFileAnnotation.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/isFlowFileAnnotation'>;
}
declare module 'eslint-plugin-flow/dist/utilities/iterateFunctionNodes.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/iterateFunctionNodes'>;
}
declare module 'eslint-plugin-flow/dist/utilities/quoteName.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/quoteName'>;
}
declare module 'eslint-plugin-flow/dist/utilities/spacingFixers.js' {
  declare module.exports: $Exports<'eslint-plugin-flow/dist/utilities/spacingFixers'>;
}
