// flow-typed signature: c5356e8f6b444aaae4e745ddb1abf9c3
// flow-typed version: <<STUB>>/react-move_v^1.1.8/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-move'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-move' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-move/lib/Animate' {
  declare module.exports: any;
}

declare module 'react-move/lib/Appear' {
  declare module.exports: any;
}

declare module 'react-move/lib/index' {
  declare module.exports: any;
}

declare module 'react-move/lib/Transition' {
  declare module.exports: any;
}

declare module 'react-move/lib/Utils' {
  declare module.exports: any;
}

declare module 'react-move/react-move' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-move/lib/Animate.js' {
  declare module.exports: $Exports<'react-move/lib/Animate'>;
}
declare module 'react-move/lib/Appear.js' {
  declare module.exports: $Exports<'react-move/lib/Appear'>;
}
declare module 'react-move/lib/index.js' {
  declare module.exports: $Exports<'react-move/lib/index'>;
}
declare module 'react-move/lib/Transition.js' {
  declare module.exports: $Exports<'react-move/lib/Transition'>;
}
declare module 'react-move/lib/Utils.js' {
  declare module.exports: $Exports<'react-move/lib/Utils'>;
}
declare module 'react-move/react-move.js' {
  declare module.exports: $Exports<'react-move/react-move'>;
}
