// flow-typed signature: d716ab024373508ce2426d20968e8586
// flow-typed version: <<STUB>>/react-share_v^1.15.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-share'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-share' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-share/lib/generateIcon' {
  declare module.exports: any;
}

declare module 'react-share/lib/icons' {
  declare module.exports: any;
}

declare module 'react-share/lib/react-share' {
  declare module.exports: any;
}

declare module 'react-share/lib/share-buttons' {
  declare module.exports: any;
}

declare module 'react-share/lib/share-count-getters' {
  declare module.exports: any;
}

declare module 'react-share/lib/share-counts' {
  declare module.exports: any;
}

declare module 'react-share/lib/social-media-share-links' {
  declare module.exports: any;
}

declare module 'react-share/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-share/lib/generateIcon.js' {
  declare module.exports: $Exports<'react-share/lib/generateIcon'>;
}
declare module 'react-share/lib/icons.js' {
  declare module.exports: $Exports<'react-share/lib/icons'>;
}
declare module 'react-share/lib/react-share.js' {
  declare module.exports: $Exports<'react-share/lib/react-share'>;
}
declare module 'react-share/lib/share-buttons.js' {
  declare module.exports: $Exports<'react-share/lib/share-buttons'>;
}
declare module 'react-share/lib/share-count-getters.js' {
  declare module.exports: $Exports<'react-share/lib/share-count-getters'>;
}
declare module 'react-share/lib/share-counts.js' {
  declare module.exports: $Exports<'react-share/lib/share-counts'>;
}
declare module 'react-share/lib/social-media-share-links.js' {
  declare module.exports: $Exports<'react-share/lib/social-media-share-links'>;
}
declare module 'react-share/lib/utils.js' {
  declare module.exports: $Exports<'react-share/lib/utils'>;
}
