// flow-typed signature: 7a54baafcc06a92f8eeadce0599ccf95
// flow-typed version: <<STUB>>/webpack-manifest-plugin_v1.1.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-manifest-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-manifest-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-manifest-plugin/lib/plugin' {
  declare module.exports: any;
}

declare module 'webpack-manifest-plugin/spec/fixtures/file-two' {
  declare module.exports: any;
}

declare module 'webpack-manifest-plugin/spec/fixtures/file' {
  declare module.exports: any;
}

declare module 'webpack-manifest-plugin/spec/fixtures/nameless' {
  declare module.exports: any;
}

declare module 'webpack-manifest-plugin/spec/plugin.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-manifest-plugin/index' {
  declare module.exports: $Exports<'webpack-manifest-plugin'>;
}
declare module 'webpack-manifest-plugin/index.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin'>;
}
declare module 'webpack-manifest-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin/lib/plugin'>;
}
declare module 'webpack-manifest-plugin/spec/fixtures/file-two.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin/spec/fixtures/file-two'>;
}
declare module 'webpack-manifest-plugin/spec/fixtures/file.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin/spec/fixtures/file'>;
}
declare module 'webpack-manifest-plugin/spec/fixtures/nameless.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin/spec/fixtures/nameless'>;
}
declare module 'webpack-manifest-plugin/spec/plugin.spec.js' {
  declare module.exports: $Exports<'webpack-manifest-plugin/spec/plugin.spec'>;
}
