#!/usr/bin/env bash
# Runs Claude Code in a loop to generate and curate training data.
#
# Requires: claude CLI on PATH (logged in - iterations run on your Claude Code
# subscription), and env vars
#   DC_API_URL  - deployed Worker URL (e.g. https://grabient-data-collection.<acct>.workers.dev)
#   DC_API_KEY  - value of the HARNESS_API_KEY secret
# Both are auto-loaded from harness/.env (gitignored) if it exists.
#
# Usage: pnpm harness:loop [max_iterations]   (default: run forever)
#
# LOOP_ROLE env splits work across parallel loops without duplicate-work waste:
#   all      - default; full mode schedule in one loop
#   generate - generate/caption/audit only (never judges)
#   judge    - drains the judge queue whenever pending pairs exist; audits
#              periodically; idles cheaply when there is nothing to score
# Run one generate loop + one judge loop for ~2x wall-clock throughput; do NOT
# run two generate loops (they converge on similar palettes and waste tokens
# on duplicate rejections).
set -uo pipefail

cd "$(dirname "$0")/.."

if [ -f harness/.env ]; then
  set -a
  # shellcheck disable=SC1091
  . harness/.env
  set +a
fi

: "${DC_API_URL:?set DC_API_URL to the deployed worker URL}"
: "${DC_API_KEY:?set DC_API_KEY to the HARNESS_API_KEY secret}"
export DC_API_URL DC_API_KEY

# Headless child sessions cannot reliably expand env vars (the sandbox blocks
# env reads intermittently and there is no human to approve an escalation), so
# bake the credentials into a gitignored wrapper the skills invoke instead.
{
  echo '#!/usr/bin/env bash'
  echo '# generated by loop.sh from harness/.env - gitignored, do not commit'
  echo 'path="$1"; shift'
  printf 'exec curl -sf -H "Authorization: Bearer %s" "$@" "%s${path}"\n' \
    "$DC_API_KEY" "$DC_API_URL"
} > harness/dc-api.sh
chmod +x harness/dc-api.sh

MAX_ITERATIONS="${1:-0}" # 0 = forever
LOOP_ROLE="${LOOP_ROLE:-all}"
SLEEP_BETWEEN="${LOOP_SLEEP:-30}"
FAILURE_BACKOFF=300
JUDGE_BACKLOG_THRESHOLD="${JUDGE_BACKLOG_THRESHOLD:-150}"
JUDGE_IDLE_SLEEP=120 # judge role: wait this long when there is nothing to score
ITERATION_TIMEOUT="15m"
LOG_DIR="harness/logs"
mkdir -p "$LOG_DIR"

# Housekeeping so an unattended loop doesn't fill the disk.
find "$LOG_DIR" -name '*.log' -mtime +7 -delete 2>/dev/null || true
find harness/renders -type f -mtime +2 -delete 2>/dev/null || true

api() {
  curl -sf -H "Authorization: Bearer $DC_API_KEY" "$DC_API_URL$1"
}

iteration=0
consecutive_failures=0

while true; do
  iteration=$((iteration + 1))
  if [ "$MAX_ITERATIONS" -gt 0 ] && [ "$iteration" -gt "$MAX_ITERATIONS" ]; then
    echo "done: reached $MAX_ITERATIONS iterations"
    break
  fi

  pending=$(api /api/stats | python3 -c 'import json,sys; print(json.load(sys.stdin).get("pairs",{}).get("pending",0))' 2>/dev/null || echo 0)

  # Mode schedule per role.
  case "$LOOP_ROLE" in
    judge)
      # Dedicated judge loop: drain whenever there is work, audit every 12th,
      # otherwise idle cheaply (no claude invocation at all).
      if [ $((iteration % 12)) -eq 0 ] && [ "$pending" -lt 8 ]; then
        mode="audit"
      elif [ "$pending" -gt 0 ]; then
        mode="judge"
      else
        echo "[$(date +%H:%M:%S)] judge idle (pending: 0); sleeping ${JUDGE_IDLE_SLEEP}s"
        sleep "$JUDGE_IDLE_SLEEP"
        continue
      fi
      ;;
    generate)
      # Volume loop: never judges (a judge-role loop handles that). Backs off
      # when the judge queue is deep - unscored pairs are inventory, not
      # progress, and pausing here lets the judge spend the token budget.
      if [ "$pending" -gt "${GEN_BACKPRESSURE:-600}" ]; then
        echo "[$(date +%H:%M:%S)] backpressure: $pending pending pairs; pausing generation 180s"
        sleep 180
        continue
      fi
      if [ $((iteration % 12)) -eq 0 ]; then
        mode="audit"
      elif [ $((iteration % 4)) -eq 0 ]; then
        mode="caption"
      else
        mode="generate-forward"
      fi
      ;;
    *)
      # Single-loop schedule: keep the judge queue drained, sample coeff space
      # every 3rd iteration (then caption it), audit every 12th, else generate.
      if [ "$pending" -gt "$JUDGE_BACKLOG_THRESHOLD" ]; then
        mode="judge"
      elif [ $((iteration % 12)) -eq 0 ]; then
        mode="audit"
      elif [ $((iteration % 3)) -eq 0 ]; then
        mode="caption"
      else
        mode="generate-forward"
      fi
      ;;
  esac

  # Volume modes run on sonnet to stretch subscription usage; judge/audit are
  # the dataset's quality gate and get the stronger model. Turn caps are
  # generous on purpose - an undersized cap kills the iteration mid-work and
  # wastes everything it spent. Tighten per-mode only after logs show real
  # turn counts well under the cap.
  case "$mode" in
    judge|audit) model="opus"   ;;
    *)           model="sonnet" ;;
  esac
  max_turns=50

  # Decorrelate generation: fresh contexts given identical prompts converge on
  # the same favorite palettes. Two random themes per iteration - the collision
  # of unrelated concepts is where the unusual queries come from.
  focus=""
  if [ "$mode" = "generate-forward" ] && [ -s harness/themes.txt ]; then
    focus="$(shuf -n2 harness/themes.txt | paste -sd'|')"
  fi

  run_id="$(date +%Y%m%d-%H%M%S)-$$-$mode"
  log_file="$LOG_DIR/$run_id.log"
  echo "[$(date +%H:%M:%S)] iteration $iteration mode=$mode model=$model run=$run_id (pending pairs: $pending)${focus:+ focus='$focus'}"

  curl -sf -X POST -H "Authorization: Bearer $DC_API_KEY" -H "Content-Type: application/json" \
    -d "{\"id\":\"$run_id\",\"mode\":\"$mode\"}" "$DC_API_URL/api/runs" >/dev/null || true

  # Deterministic coeff-space sampling runs before captioning so there is
  # always something to caption.
  if [ "$mode" = "caption" ]; then
    npx tsx harness/sample.ts --run-id "$run_id" >>"$log_file" 2>&1 || true
  fi
  # Judge works best with rendered previews; pre-render the queue to PNGs.
  # Per-run render dirs: parallel judge loops must never share one (render.ts
  # wipes its dir first). Batches of 30 balance per-iteration overhead against
  # the cost of a long opus session dying mid-run.
  render_dir=""
  if [ "$mode" = "judge" ] || [ "$mode" = "audit" ]; then
    render_limit=24
    [ "$mode" = "judge" ] && render_limit=30
    render_dir="harness/renders/$run_id"
    npx tsx harness/render.ts --mode "$mode" --run-id "$run_id" --limit "$render_limit" --out-dir "$render_dir" >>"$log_file" 2>&1 || true
  fi

  if timeout "$ITERATION_TIMEOUT" claude -p "/$mode run_id=$run_id${render_dir:+ render_dir=$render_dir}${focus:+ focus=\"$focus\"}" \
    --model "$model" \
    --allowedTools "Bash(curl:*),Bash(harness/dc-api.sh:*),Bash(bash harness/dc-api.sh:*),Bash(./harness/dc-api.sh:*),Bash(npx tsx harness/*),Read" \
    --max-turns "$max_turns" >>"$log_file" 2>&1; then
    status="done"
    consecutive_failures=0
  else
    status="failed"
    consecutive_failures=$((consecutive_failures + 1))
    echo "  iteration failed (see $log_file)"
  fi

  curl -sf -X PATCH -H "Authorization: Bearer $DC_API_KEY" -H "Content-Type: application/json" \
    -d "{\"status\":\"$status\"}" "$DC_API_URL/api/runs/$run_id" >/dev/null || true

  # Successful runs clean their render dir; failed ones keep it for debugging
  # (startup housekeeping prunes stragglers).
  if [ "$status" = "done" ] && [ -n "$render_dir" ]; then
    rm -rf "$render_dir"
  fi

  tail -2 "$log_file" 2>/dev/null | sed 's/^/  /'

  if [ "$consecutive_failures" -ge 3 ]; then
    echo "  3 consecutive failures; backing off ${FAILURE_BACKOFF}s"
    sleep "$FAILURE_BACKOFF"
    consecutive_failures=0
  else
    sleep "$SLEEP_BETWEEN"
  fi
done
