/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PaletteListRouteImport } from './routes/_paletteList'
import { Route as SeedRouteRouteImport } from './routes/$seed.route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PaletteListIndexRouteImport } from './routes/_paletteList/index'
import { Route as SeedIndexRouteImport } from './routes/$seed/index'
import { Route as PalettesQueryRouteImport } from './routes/palettes/$query'
import { Route as ESplatRouteImport } from './routes/e.$'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as PaletteListSavedRouteImport } from './routes/_paletteList/saved'
import { Route as PaletteListOldestRouteImport } from './routes/_paletteList/oldest'
import { Route as PaletteListNewestRouteImport } from './routes/_paletteList/newest'
import { Route as PalettesQueryIndexRouteImport } from './routes/palettes/$query/index'
import { Route as PalettesQueryGenerateRouteImport } from './routes/palettes/$query/generate'
import { Route as ApiOgQueryRouteImport } from './routes/api/og.query'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PaletteListRoute = PaletteListRouteImport.update({
  id: '/_paletteList',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedRouteRoute = SeedRouteRouteImport.update({
  id: '/$seed',
  path: '/$seed',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaletteListIndexRoute = PaletteListIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaletteListRoute,
} as any)
const SeedIndexRoute = SeedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeedRouteRoute,
} as any)
const PalettesQueryRoute = PalettesQueryRouteImport.update({
  id: '/palettes/$query',
  path: '/palettes/$query',
  getParentRoute: () => rootRouteImport,
} as any)
const ESplatRoute = ESplatRouteImport.update({
  id: '/e/$',
  path: '/e/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const PaletteListSavedRoute = PaletteListSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => PaletteListRoute,
} as any)
const PaletteListOldestRoute = PaletteListOldestRouteImport.update({
  id: '/oldest',
  path: '/oldest',
  getParentRoute: () => PaletteListRoute,
} as any)
const PaletteListNewestRoute = PaletteListNewestRouteImport.update({
  id: '/newest',
  path: '/newest',
  getParentRoute: () => PaletteListRoute,
} as any)
const PalettesQueryIndexRoute = PalettesQueryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PalettesQueryRoute,
} as any)
const PalettesQueryGenerateRoute = PalettesQueryGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => PalettesQueryRoute,
} as any)
const ApiOgQueryRoute = ApiOgQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => ApiOgRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$seed': typeof SeedRouteRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/newest': typeof PaletteListNewestRoute
  '/oldest': typeof PaletteListOldestRoute
  '/saved': typeof PaletteListSavedRoute
  '/api/og': typeof ApiOgRouteWithChildren
  '/e/$': typeof ESplatRoute
  '/palettes/$query': typeof PalettesQueryRouteWithChildren
  '/$seed/': typeof SeedIndexRoute
  '/': typeof PaletteListIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/query': typeof ApiOgQueryRoute
  '/palettes/$query/generate': typeof PalettesQueryGenerateRoute
  '/palettes/$query/': typeof PalettesQueryIndexRoute
}
export interface FileRoutesByTo {
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/newest': typeof PaletteListNewestRoute
  '/oldest': typeof PaletteListOldestRoute
  '/saved': typeof PaletteListSavedRoute
  '/api/og': typeof ApiOgRouteWithChildren
  '/e/$': typeof ESplatRoute
  '/$seed': typeof SeedIndexRoute
  '/': typeof PaletteListIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/query': typeof ApiOgQueryRoute
  '/palettes/$query/generate': typeof PalettesQueryGenerateRoute
  '/palettes/$query': typeof PalettesQueryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$seed': typeof SeedRouteRouteWithChildren
  '/_paletteList': typeof PaletteListRouteWithChildren
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_paletteList/newest': typeof PaletteListNewestRoute
  '/_paletteList/oldest': typeof PaletteListOldestRoute
  '/_paletteList/saved': typeof PaletteListSavedRoute
  '/api/og': typeof ApiOgRouteWithChildren
  '/e/$': typeof ESplatRoute
  '/palettes/$query': typeof PalettesQueryRouteWithChildren
  '/$seed/': typeof SeedIndexRoute
  '/_paletteList/': typeof PaletteListIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/og/query': typeof ApiOgQueryRoute
  '/palettes/$query/generate': typeof PalettesQueryGenerateRoute
  '/palettes/$query/': typeof PalettesQueryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$seed'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/newest'
    | '/oldest'
    | '/saved'
    | '/api/og'
    | '/e/$'
    | '/palettes/$query'
    | '/$seed/'
    | '/'
    | '/settings'
    | '/api/auth/$'
    | '/api/og/query'
    | '/palettes/$query/generate'
    | '/palettes/$query/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/newest'
    | '/oldest'
    | '/saved'
    | '/api/og'
    | '/e/$'
    | '/$seed'
    | '/'
    | '/settings'
    | '/api/auth/$'
    | '/api/og/query'
    | '/palettes/$query/generate'
    | '/palettes/$query'
  id:
    | '__root__'
    | '/$seed'
    | '/_paletteList'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/_paletteList/newest'
    | '/_paletteList/oldest'
    | '/_paletteList/saved'
    | '/api/og'
    | '/e/$'
    | '/palettes/$query'
    | '/$seed/'
    | '/_paletteList/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/og/query'
    | '/palettes/$query/generate'
    | '/palettes/$query/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SeedRouteRoute: typeof SeedRouteRouteWithChildren
  PaletteListRoute: typeof PaletteListRouteWithChildren
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiOgRoute: typeof ApiOgRouteWithChildren
  ESplatRoute: typeof ESplatRoute
  PalettesQueryRoute: typeof PalettesQueryRouteWithChildren
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_paletteList': {
      id: '/_paletteList'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PaletteListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$seed': {
      id: '/$seed'
      path: '/$seed'
      fullPath: '/$seed'
      preLoaderRoute: typeof SeedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_paletteList/': {
      id: '/_paletteList/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PaletteListIndexRouteImport
      parentRoute: typeof PaletteListRoute
    }
    '/$seed/': {
      id: '/$seed/'
      path: '/'
      fullPath: '/$seed/'
      preLoaderRoute: typeof SeedIndexRouteImport
      parentRoute: typeof SeedRouteRoute
    }
    '/palettes/$query': {
      id: '/palettes/$query'
      path: '/palettes/$query'
      fullPath: '/palettes/$query'
      preLoaderRoute: typeof PalettesQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$': {
      id: '/e/$'
      path: '/e/$'
      fullPath: '/e/$'
      preLoaderRoute: typeof ESplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_paletteList/saved': {
      id: '/_paletteList/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof PaletteListSavedRouteImport
      parentRoute: typeof PaletteListRoute
    }
    '/_paletteList/oldest': {
      id: '/_paletteList/oldest'
      path: '/oldest'
      fullPath: '/oldest'
      preLoaderRoute: typeof PaletteListOldestRouteImport
      parentRoute: typeof PaletteListRoute
    }
    '/_paletteList/newest': {
      id: '/_paletteList/newest'
      path: '/newest'
      fullPath: '/newest'
      preLoaderRoute: typeof PaletteListNewestRouteImport
      parentRoute: typeof PaletteListRoute
    }
    '/palettes/$query/': {
      id: '/palettes/$query/'
      path: '/'
      fullPath: '/palettes/$query/'
      preLoaderRoute: typeof PalettesQueryIndexRouteImport
      parentRoute: typeof PalettesQueryRoute
    }
    '/palettes/$query/generate': {
      id: '/palettes/$query/generate'
      path: '/generate'
      fullPath: '/palettes/$query/generate'
      preLoaderRoute: typeof PalettesQueryGenerateRouteImport
      parentRoute: typeof PalettesQueryRoute
    }
    '/api/og/query': {
      id: '/api/og/query'
      path: '/query'
      fullPath: '/api/og/query'
      preLoaderRoute: typeof ApiOgQueryRouteImport
      parentRoute: typeof ApiOgRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SeedRouteRouteChildren {
  SeedIndexRoute: typeof SeedIndexRoute
}

const SeedRouteRouteChildren: SeedRouteRouteChildren = {
  SeedIndexRoute: SeedIndexRoute,
}

const SeedRouteRouteWithChildren = SeedRouteRoute._addFileChildren(
  SeedRouteRouteChildren,
)

interface PaletteListRouteChildren {
  PaletteListNewestRoute: typeof PaletteListNewestRoute
  PaletteListOldestRoute: typeof PaletteListOldestRoute
  PaletteListSavedRoute: typeof PaletteListSavedRoute
  PaletteListIndexRoute: typeof PaletteListIndexRoute
}

const PaletteListRouteChildren: PaletteListRouteChildren = {
  PaletteListNewestRoute: PaletteListNewestRoute,
  PaletteListOldestRoute: PaletteListOldestRoute,
  PaletteListSavedRoute: PaletteListSavedRoute,
  PaletteListIndexRoute: PaletteListIndexRoute,
}

const PaletteListRouteWithChildren = PaletteListRoute._addFileChildren(
  PaletteListRouteChildren,
)

interface ApiOgRouteChildren {
  ApiOgQueryRoute: typeof ApiOgQueryRoute
}

const ApiOgRouteChildren: ApiOgRouteChildren = {
  ApiOgQueryRoute: ApiOgQueryRoute,
}

const ApiOgRouteWithChildren = ApiOgRoute._addFileChildren(ApiOgRouteChildren)

interface PalettesQueryRouteChildren {
  PalettesQueryGenerateRoute: typeof PalettesQueryGenerateRoute
  PalettesQueryIndexRoute: typeof PalettesQueryIndexRoute
}

const PalettesQueryRouteChildren: PalettesQueryRouteChildren = {
  PalettesQueryGenerateRoute: PalettesQueryGenerateRoute,
  PalettesQueryIndexRoute: PalettesQueryIndexRoute,
}

const PalettesQueryRouteWithChildren = PalettesQueryRoute._addFileChildren(
  PalettesQueryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SeedRouteRoute: SeedRouteRouteWithChildren,
  PaletteListRoute: PaletteListRouteWithChildren,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiOgRoute: ApiOgRouteWithChildren,
  ESplatRoute: ESplatRoute,
  PalettesQueryRoute: PalettesQueryRouteWithChildren,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
