/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutRandomRouteImport } from './routes/_layout/random'
import { Route as LayoutGenerateRouteImport } from './routes/_layout/generate'
import { Route as LayoutSeedRouteImport } from './routes/_layout/$seed'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRandomRoute = LayoutRandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGenerateRoute = LayoutGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSeedRoute = LayoutSeedRouteImport.update({
  id: '/$seed',
  path: '/$seed',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$seed': typeof LayoutSeedRoute
  '/generate': typeof LayoutGenerateRoute
  '/random': typeof LayoutRandomRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/$seed': typeof LayoutSeedRoute
  '/generate': typeof LayoutGenerateRoute
  '/random': typeof LayoutRandomRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/$seed': typeof LayoutSeedRoute
  '/_layout/generate': typeof LayoutGenerateRoute
  '/_layout/random': typeof LayoutRandomRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$seed' | '/generate' | '/random' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$seed' | '/generate' | '/random' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/$seed'
    | '/_layout/generate'
    | '/_layout/random'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/random': {
      id: '/_layout/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof LayoutRandomRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/generate': {
      id: '/_layout/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof LayoutGenerateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$seed': {
      id: '/_layout/$seed'
      path: '/$seed'
      fullPath: '/$seed'
      preLoaderRoute: typeof LayoutSeedRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSeedRoute: typeof LayoutSeedRoute
  LayoutGenerateRoute: typeof LayoutGenerateRoute
  LayoutRandomRoute: typeof LayoutRandomRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSeedRoute: LayoutSeedRoute,
  LayoutGenerateRoute: LayoutGenerateRoute,
  LayoutRandomRoute: LayoutRandomRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
