-- grabient-admin 0004: reports and period digests.
--
-- One table, two kinds:
--   kind='report'  free-form markdown written by an agent through MCP
--   kind='digest'  a period brief generated by the cron from live metrics
-- They share a URL space, an archive and a retrieval path; they differ only
-- in the period_* columns and payload_json, all nullable for reports.

CREATE TABLE reports (
  id            TEXT    PRIMARY KEY,           -- opaque, time-sortable
  -- URL identity, IMMUTABLE: the link has already been handed to a human.
  -- Deliberately NOT a partial unique — a soft-deleted slug stays reserved so
  -- a bookmarked URL can never come back as different content.
  slug          TEXT    NOT NULL UNIQUE,
  kind          TEXT    NOT NULL CHECK (kind IN ('report','digest')),
  title         TEXT    NOT NULL CHECK (length(title) BETWEEN 3 AND 200),
  summary       TEXT             CHECK (summary IS NULL OR length(summary) <= 280),
  -- 256 KB byte cap, enforced in the tool for a usable error and here so a
  -- future code path cannot bypass it. CAST AS BLOB measures BYTES.
  body_md       TEXT    NOT NULL CHECK (length(CAST(body_md AS BLOB)) <= 262144),
  payload_json  TEXT             CHECK (payload_json IS NULL
                                        OR length(CAST(payload_json AS BLOB)) <= 131072),
  period_type   TEXT             CHECK (period_type IS NULL
                                        OR period_type IN ('day','week','month','quarter')),
  period_start  TEXT,                          -- 'YYYY-MM-DD' UTC, inclusive
  period_end    TEXT,                          -- 'YYYY-MM-DD' UTC, inclusive
  author        TEXT    NOT NULL CHECK (author IN ('agent','cron','human')),
  author_ref    TEXT,                          -- the Access identity that wrote it
  tags          TEXT,                          -- JSON array of strings
  revision      INTEGER NOT NULL DEFAULT 1,
  bytes         INTEGER NOT NULL,
  created_at    INTEGER NOT NULL,
  updated_at    INTEGER NOT NULL,
  deleted_at    INTEGER
);

CREATE INDEX reports_recent  ON reports (created_at DESC, id DESC) WHERE deleted_at IS NULL;
CREATE INDEX reports_by_kind ON reports (kind, created_at DESC, id DESC) WHERE deleted_at IS NULL;

-- Makes the digest cron idempotent: re-running Monday's job upserts the same
-- weekly digest rather than minting a second. Scoped to digests, so an agent
-- may still write a free-form report about the same period.
CREATE UNIQUE INDEX reports_one_digest_per_period
  ON reports (period_type, period_start)
  WHERE kind = 'digest' AND deleted_at IS NULL;

-- Append-only history: the current version lives in `reports`, this is what
-- the previous version was — so an agent overwriting a good report with a
-- worse one is recoverable without a database-wide Time Travel restore.
CREATE TABLE report_revisions (
  report_id  TEXT    NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  revision   INTEGER NOT NULL,
  title      TEXT    NOT NULL,
  body_md    TEXT    NOT NULL,
  author_ref TEXT,
  created_at INTEGER NOT NULL,
  PRIMARY KEY (report_id, revision)
);
